// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StopGame.Infrastructure.Data;

#nullable disable

namespace StopGame.Infrastructure.Migrations
{
    [DbContext(typeof(StopGameDbContext))]
    [Migration("20250702190937_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StopGame.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe8e1285-e936-481b-b7ea-95b57b709a33"),
                            CreatedAt = new DateTime(2025, 7, 2, 19, 9, 37, 568, DateTimeKind.Utc).AddTicks(4861),
                            IsDefault = true,
                            Name = "Animal"
                        },
                        new
                        {
                            Id = new Guid("a8db7a67-491b-41ac-944d-6776627bfcb1"),
                            CreatedAt = new DateTime(2025, 7, 2, 19, 9, 37, 568, DateTimeKind.Utc).AddTicks(4864),
                            IsDefault = true,
                            Name = "Country"
                        },
                        new
                        {
                            Id = new Guid("24ced846-73f1-409c-8464-6349fedc2ad7"),
                            CreatedAt = new DateTime(2025, 7, 2, 19, 9, 37, 568, DateTimeKind.Utc).AddTicks(4865),
                            IsDefault = true,
                            Name = "City"
                        },
                        new
                        {
                            Id = new Guid("d9795da9-b89e-4235-a6a8-fbd5f61ff09c"),
                            CreatedAt = new DateTime(2025, 7, 2, 19, 9, 37, 568, DateTimeKind.Utc).AddTicks(4866),
                            IsDefault = true,
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("268ff43f-c261-4b7d-9784-0eab83c4ef0c"),
                            CreatedAt = new DateTime(2025, 7, 2, 19, 9, 37, 568, DateTimeKind.Utc).AddTicks(4867),
                            IsDefault = true,
                            Name = "Color"
                        },
                        new
                        {
                            Id = new Guid("382c98fd-7f3b-4935-be94-5f513a8abc1e"),
                            CreatedAt = new DateTime(2025, 7, 2, 19, 9, 37, 568, DateTimeKind.Utc).AddTicks(4869),
                            IsDefault = true,
                            Name = "Name"
                        },
                        new
                        {
                            Id = new Guid("7234761e-0fab-4895-9622-5de653ab6835"),
                            CreatedAt = new DateTime(2025, 7, 2, 19, 9, 37, 568, DateTimeKind.Utc).AddTicks(4870),
                            IsDefault = true,
                            Name = "Profession"
                        },
                        new
                        {
                            Id = new Guid("7ee6b65e-4416-423b-aa6c-e8bda86a6369"),
                            CreatedAt = new DateTime(2025, 7, 2, 19, 9, 37, 568, DateTimeKind.Utc).AddTicks(4875),
                            IsDefault = true,
                            Name = "Movie"
                        },
                        new
                        {
                            Id = new Guid("c2040d1a-f439-4a05-b656-b606bf73cc80"),
                            CreatedAt = new DateTime(2025, 7, 2, 19, 9, 37, 568, DateTimeKind.Utc).AddTicks(4876),
                            IsDefault = true,
                            Name = "Brand"
                        },
                        new
                        {
                            Id = new Guid("063e535f-e823-4eb6-a760-3975adc25e22"),
                            CreatedAt = new DateTime(2025, 7, 2, 19, 9, 37, 568, DateTimeKind.Utc).AddTicks(4877),
                            IsDefault = true,
                            Name = "Sport"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
